export default {
  Linechart: {
    width: 350,
    height: 220,
    gradient: {
      startColor: '#67b9f6',
      stopColor: '#406ec9',
      startOpacity: '0.5',
      stopOpacity: '1',
    },
    chartMargins: {
      left: -17,
      right: 35,
      top: 0,
      bottom: 0,
    },
    margins: {
      top: 5,
      left: 5,
      right: 5,
      bottom: 5,
    },
    bottomBorderMargin: -16,
    incomeLineMargin: 5,
    lineColor: '#67b9f6',
    lineColorGood: '#33bf82',
    lineColorBad: '#ed5f79',
    areaFillColor: '#e6edf3',
    textColor: '#94a6bd',
    axisLineColor: '#e6edf3',
    axisStrokeWidth: 1,
    pointDateMargin: -3,
    pointFillColor: '#fff',
    pointOutlineColor: '#406ec9',
    netWorthPointOutlineColor: '#67b9f6',
    pointLineColorDark: '#404862',
    pointLineColorLight: '#e6edf3',
    lineStrokeWidth: 2.2,
    areaStrokeWidth: 0,
    pointRadius: 5,
    pointStrokeWidth: 2,
    lineDashoffset: 22,
    lineDasharray: 5,
    lineOpacity: 0.58,
  },
  Donutchart: {
    width: 327,
    height: 264,
    arcStrokeColor: 'transparent',
    arcFillColor: '#67b9f6',
    TextColorLight: '#fff',
    TextColorDark: '#67b9f6',
    arcStyle: {
      arcWidth: 33,
      arcMargin: 4,
      ringSize: 88,
    },
  },
};
